# Generated by Django 6.1 on 2026-08-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OlaMundo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(default='111.111.111-11', max_length=14),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='remuneracao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='sobrenome',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='tempo_de_servico',
            field=models.IntegerField(default=0),
        ),
    ]
